/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccountDetails struct {

	Type_ string `json:"type,omitempty"`

	Environment string `json:"environment,omitempty"`

	Permissions map[string][]string `json:"permissions,omitempty"`

	AccountType string `json:"accountType,omitempty"`

	ChallengeDestructiveActions bool `json:"challengeDestructiveActions,omitempty"`

	RequiredGroupMembership []string `json:"requiredGroupMembership,omitempty"`

	CloudProvider string `json:"cloudProvider,omitempty"`

	Name string `json:"name,omitempty"`

	PrimaryAccount bool `json:"primaryAccount,omitempty"`

	AccountId string `json:"accountId,omitempty"`

	Skin string `json:"skin,omitempty"`

	ProviderVersion string `json:"providerVersion,omitempty"`
}
