/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ConstraintState struct {
	JudgedAt string `json:"judgedAt,omitempty"`

	JudgedBy string `json:"judgedBy,omitempty"`

	DeliveryConfigName string `json:"deliveryConfigName,omitempty"`

	Attributes *interface{} `json:"attributes,omitempty"`

	CreatedAt string `json:"createdAt,omitempty"`

	ArtifactVersion string `json:"artifactVersion,omitempty"`

	Type_ string `json:"type,omitempty"`

	EnvironmentName string `json:"environmentName,omitempty"`

	Status string `json:"status,omitempty"`

	Comment string `json:"comment,omitempty"`
}
