/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ConstraintState struct {
	ArtifactVersion    string       `json:"artifactVersion,omitempty"`
	JudgedBy           string       `json:"judgedBy,omitempty"`
	EnvironmentName    string       `json:"environmentName,omitempty"`
	CreatedAt          string       `json:"createdAt,omitempty"`
	DeliveryConfigName string       `json:"deliveryConfigName,omitempty"`
	Status             string       `json:"status,omitempty"`
	Type_              string       `json:"type,omitempty"`
	Comment            string       `json:"comment,omitempty"`
	JudgedAt           string       `json:"judgedAt,omitempty"`
	Attributes         *interface{} `json:"attributes,omitempty"`
}
