/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SpinnakerPluginInfo struct {
	RepositoryId string                   `json:"repositoryId,omitempty"`
	Id           string                   `json:"id,omitempty"`
	Releases     []SpinnakerPluginRelease `json:"releases"`
	Name         string                   `json:"name,omitempty"`
	Provider     string                   `json:"provider,omitempty"`
	Description  string                   `json:"description,omitempty"`
	ProjectUrl   string                   `json:"projectUrl,omitempty"`
}
