/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SpinnakerPluginDescriptor struct {
	PluginId string `json:"pluginId,omitempty"`
	Requires string `json:"requires,omitempty"`
	PluginClass string `json:"pluginClass,omitempty"`
	Version string `json:"version,omitempty"`
	Dependencies []PluginDependency `json:"dependencies,omitempty"`
	Unsafe bool `json:"unsafe"`
	PluginDescription string `json:"pluginDescription,omitempty"`
	Provider string `json:"provider,omitempty"`
	License string `json:"license,omitempty"`
}
