/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"os"
)

type File struct {
	File          bool      `json:"file,omitempty"`
	Writable      bool      `json:"writable,omitempty"`
	Executable    bool      `json:"executable,omitempty"`
	Hidden        bool      `json:"hidden,omitempty"`
	Path          string    `json:"path,omitempty"`
	UsableSpace   int64     `json:"usableSpace,omitempty"`
	Parent        string    `json:"parent,omitempty"`
	Directory     bool      `json:"directory,omitempty"`
	Absolute      bool      `json:"absolute,omitempty"`
	CanonicalFile **os.File `json:"canonicalFile,omitempty"`
	Readable      bool      `json:"readable,omitempty"`
	ParentFile    **os.File `json:"parentFile,omitempty"`
	Name          string    `json:"name,omitempty"`
	TotalSpace    int64     `json:"totalSpace,omitempty"`
	AbsolutePath  string    `json:"absolutePath,omitempty"`
	FreeSpace     int64     `json:"freeSpace,omitempty"`
	AbsoluteFile  **os.File `json:"absoluteFile,omitempty"`
	CanonicalPath string    `json:"canonicalPath,omitempty"`
	LastModified  int64     `json:"lastModified,omitempty"`
}
