/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"os"
)

type File struct {
	CanonicalFile **os.File `json:"canonicalFile,omitempty"`
	AbsolutePath string `json:"absolutePath,omitempty"`
	Path string `json:"path,omitempty"`
	UsableSpace int64 `json:"usableSpace,omitempty"`
	Absolute bool `json:"absolute,omitempty"`
	Writable bool `json:"writable,omitempty"`
	File bool `json:"file,omitempty"`
	Readable bool `json:"readable,omitempty"`
	AbsoluteFile **os.File `json:"absoluteFile,omitempty"`
	Name string `json:"name,omitempty"`
	ParentFile **os.File `json:"parentFile,omitempty"`
	FreeSpace int64 `json:"freeSpace,omitempty"`
	Hidden bool `json:"hidden,omitempty"`
	Parent string `json:"parent,omitempty"`
	Executable bool `json:"executable,omitempty"`
	TotalSpace int64 `json:"totalSpace,omitempty"`
	LastModified int64 `json:"lastModified,omitempty"`
	CanonicalPath string `json:"canonicalPath,omitempty"`
	Directory bool `json:"directory,omitempty"`
}
