/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Uri struct {
	RawPath               string `json:"rawPath,omitempty"`
	RawAuthority          string `json:"rawAuthority,omitempty"`
	RawQuery              string `json:"rawQuery,omitempty"`
	Port                  int32  `json:"port,omitempty"`
	SchemeSpecificPart    string `json:"schemeSpecificPart,omitempty"`
	Absolute              bool   `json:"absolute,omitempty"`
	RawSchemeSpecificPart string `json:"rawSchemeSpecificPart,omitempty"`
	Path                  string `json:"path,omitempty"`
	Scheme                string `json:"scheme,omitempty"`
	RawUserInfo           string `json:"rawUserInfo,omitempty"`
	Opaque                bool   `json:"opaque,omitempty"`
	Query                 string `json:"query,omitempty"`
	Authority             string `json:"authority,omitempty"`
	UserInfo              string `json:"userInfo,omitempty"`
	Fragment              string `json:"fragment,omitempty"`
	Host                  string `json:"host,omitempty"`
	RawFragment           string `json:"rawFragment,omitempty"`
}
