/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type User struct {
	FirstName string `json:"firstName,omitempty"`
	AccountNonExpired bool `json:"accountNonExpired,omitempty"`
	LastName string `json:"lastName,omitempty"`
	Email string `json:"email,omitempty"`
	Authorities []GrantedAuthority `json:"authorities,omitempty"`
	CredentialsNonExpired bool `json:"credentialsNonExpired,omitempty"`
	AllowedAccounts []string `json:"allowedAccounts,omitempty"`
	Roles []string `json:"roles,omitempty"`
	AccountNonLocked bool `json:"accountNonLocked,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Username string `json:"username,omitempty"`
}
