/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DeliveryConfig struct {
	Application string `json:"application,omitempty"`
	Artifacts []Mapstringobject `json:"artifacts,omitempty"`
	ServiceAccount string `json:"serviceAccount,omitempty"`
	ApiVersion string `json:"apiVersion,omitempty"`
	Name string `json:"name,omitempty"`
	Environments []Environment `json:"environments,omitempty"`
}
