/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ConstraintState struct {
	Type_ string `json:"type,omitempty"`
	Comment string `json:"comment,omitempty"`
	Attributes *interface{} `json:"attributes,omitempty"`
	ArtifactVersion string `json:"artifactVersion,omitempty"`
	Status string `json:"status,omitempty"`
	DeliveryConfigName string `json:"deliveryConfigName,omitempty"`
	JudgedBy string `json:"judgedBy,omitempty"`
	EnvironmentName string `json:"environmentName,omitempty"`
	JudgedAt string `json:"judgedAt,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
}
