/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SpinnakerPluginDescriptor struct {
	PluginClass       string             `json:"pluginClass,omitempty"`
	License           string             `json:"license,omitempty"`
	PluginId          string             `json:"pluginId,omitempty"`
	Provider          string             `json:"provider,omitempty"`
	Dependencies      []PluginDependency `json:"dependencies,omitempty"`
	Version           string             `json:"version,omitempty"`
	Requires          string             `json:"requires,omitempty"`
	PluginDescription string             `json:"pluginDescription,omitempty"`
	Unsafe            bool               `json:"unsafe"`
}
