/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Url struct {
	Content *interface{} `json:"content,omitempty"`
	File string `json:"file,omitempty"`
	DefaultPort int32 `json:"defaultPort,omitempty"`
	Ref string `json:"ref,omitempty"`
	Authority string `json:"authority,omitempty"`
	Path string `json:"path,omitempty"`
	DeserializedFields *UrlStreamHandler `json:"deserializedFields,omitempty"`
	Protocol string `json:"protocol,omitempty"`
	Host string `json:"host,omitempty"`
	UserInfo string `json:"userInfo,omitempty"`
	SerializedHashCode int32 `json:"serializedHashCode,omitempty"`
	Query string `json:"query,omitempty"`
	Port int32 `json:"port,omitempty"`
}
