/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Headers struct {
	WriteHeaders map[string]string `json:"writeHeaders,omitempty"`
	InvokeHeaders map[string]string `json:"invokeHeaders,omitempty"`
	ReadHeaders map[string]string `json:"readHeaders,omitempty"`
}
