/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type User struct {
	AllowedAccounts       []string           `json:"allowedAccounts,omitempty"`
	Enabled               bool               `json:"enabled,omitempty"`
	Roles                 []string           `json:"roles,omitempty"`
	Email                 string             `json:"email,omitempty"`
	Authorities           []GrantedAuthority `json:"authorities,omitempty"`
	CredentialsNonExpired bool               `json:"credentialsNonExpired,omitempty"`
	Username              string             `json:"username,omitempty"`
	AccountNonExpired     bool               `json:"accountNonExpired,omitempty"`
	AccountNonLocked      bool               `json:"accountNonLocked,omitempty"`
	LastName              string             `json:"lastName,omitempty"`
	FirstName             string             `json:"firstName,omitempty"`
}
